### ISSUE TITLE
Please renew certificate for uguu.se

### ISSUE THREAD

**Issue by ghost** [soufianesakhi/firefox-search-engines-helper#1]
Great extension, really helpful. Unusable right now because uguu.se certificate has expired April 29, 2018, 10:26 PM
Thanks :=)

**Comment by soufianesakhi** [comment]
Hello, I have changed the file host from uguu.se to file.io, please check if it's working for you :)

**Comment by ghost** [comment]
Hello @soufianesakhi , _Search Engines Helper **1.0.1**_ with file.io runs perfectly well.
Thanks.
