### ISSUE TITLE
Firefox Sync support

### ISSUE THREAD

**Issue by ThinkChaos** [soufianesakhi/firefox-search-engines-helper#11]
I have no idea how complex that would be, but I guess the existing JSON export/import would help a lot.

---
Thanks for this extension, I've been using it each time I need to add my custom search engines to a new Firefox install and its been great!

**Comment by soufianesakhi** [comment]
Hello,
Currently the extension has no access to the search engine data. Once you add/import them, they are stored in the `search.json.mozlz4` file in your [Firefox profile folder](http://kb.mozillazine.org/Profile_folder_-_Firefox#Navigating_to_the_profile_folder).
If Firefox does not Sync search engines by itself, there is no way to do it via the extension.

If you need an exact copy of your search engines in another Firefox profile / in a different machine, you can directly copy the `search.json.mozlz4` to the new profile folder.

**Comment by ThinkChaos** [comment]
Yeah I understand that, but its possible to implement it similarly than the import functionality, except saving it to the cloud.
The addon could even auto upload added search engines added through it. That would keep the cloud version relatively up to date.

**Comment by soufianesakhi** [comment]
The added search engines can be stored using sync. But the problem arises when importing them back in the other Firefox instance. The bulk import is currently very limited, it's just not worth the effort for this scenario: it's easier to directly copy the `search.json.mozlz4` file to the new profile directory.

**Comment by ThinkChaos** [comment]
Ah yes of course, it never crossed my mind to just drop the file in my profile directory, I went through the bulk import which is limited yeah! 😄 

Thanks for the replies.
