### ISSUE TITLE
moz4 db not valid

### ISSUE THREAD

**Issue by maxwowpow** [soufianesakhi/firefox-search-engines-helper#12]
![image](https://user-images.githubusercontent.com/169885/83939578-6ce8dd00-a7de-11ea-8f5c-d5db8ca39ab5.png)

78.0b3 x64 Win

**Comment by soufianesakhi** [comment]
Fixed in v2.1.0

**Comment by maxwowpow** [comment]
Thanks. Now it does not crash.
But.. neither export nor import works.
On export I get an empty json list.
On import some weird page opens and nothing gets imported.
Example for import:
`{"SoundCloud":{"searchURL":"http://soundcloud.com/search?q=%s","iconURL":"http://soundcloud.com/images/favicon.ico"}}`

**Comment by soufianesakhi** [comment]
What's your OS ?
I tested with Firefox 78.0b3 (64-bit) on Windows, the search engines are well exported.

On Firefox 78+, you will be presented with a page containing instructions to add/import a search engine (maybe that's the weird page you're talking about). You should use the page actions menu and click "Add Search Engine" (it's not automatic any more)

**Comment by soufianesakhi** [comment]
by the way the URL icon you're using is dead

**Comment by maxwowpow** [comment]
Ok, "it's not automatic anymore" was partially the key.

Adding a single engine (through "Add Search Engine") works only when one click on a newly open page the "Add engine" (moz-extension://4208eafa-bb76-4ba6-9174-f41fa11fd304/pages/add-search-engine.html)

- Note: Export doesn't export default engines, only custom.

- When I'm trying to import from a json file with about 100 engines and it imports somewhat with different pauses.

So I guess importing >100 engines is not very reliable as I have to control and verify manually a lot?


![image](https://user-images.githubusercontent.com/169885/83983497-39699800-a92f-11ea-9e8d-8344f94c47d9.png)

![image](https://user-images.githubusercontent.com/169885/83983508-65851900-a92f-11ea-92d9-b18a93988a34.png)

**Comment by maxwowpow** [comment]
Is there a possibility to accelerate/circumvent these limitation via Console feeding the JSON not from the disk or the `file.io` concerns the `mozlz4` file?
I just kind of want to import >100 engines as automated as possible. Thanks.

**Comment by soufianesakhi** [comment]
If you really need a "hacky" way to do it, you can try the `mozlz4-edit` add-on, but it's not very user friendly.

**Comment by maxwowpow** [comment]
Yep just found it as well myself. It solves it. Thanks!
https://addons.mozilla.org/en-US/firefox/addon/mozlz4-edit/

**Comment by maxwowpow** [comment]
I mean why can't the mozlz4 be loaded/decompressed once. Then all search engines to import parsed and converted to the "expected" format, appended to the existing engines and compressed back to mozlz4? For the "bulk"-adding option.

**Comment by soufianesakhi** [comment]
Yes I am going to implement it soon

**Comment by soufianesakhi** [comment]
Offline import added in v3.0.0 :)

**Comment by maxwowpow** [comment]
cool shite!
to your notice of the broken soundcloud icon:
I think firefox recognizes invalid icons and replaces them by some magic automatically.
