### ISSUE TITLE
Proposition: import from Google Chrome

### ISSUE THREAD

**Issue by maxwowpow** [soufianesakhi/firefox-search-engines-helper#13]
I thought I start a new issue for that.

Would you be interested in a forth button / text field for importing from Google Chrome? It seems to me like a use-case.

As the JSON/File have to be exported manually from Chrome this solution will be aimed to "advanced users" as they have to do this manually from the Dev-Console.

Two options here:

1. Let the user copy the chome's engines' list into the clipboard. 
And offer a Text-Field in the Firefox extension to paste the json directly.
_Pro_: no file in between saving/opening/selecting. Copy code is dead simple. (Script 1)

2. Add the Script 2 below to the `README.md`  and describe how to use the script for chrome.
Pro: no changes in the extension needed. Code is more complicated (Script 2).

### Integrated solution

I. Go to `chrome://settings/`
II. Press F12
III. Paste Script 1 and press Enter.
IV. Paste the clipboard to Firefox Search Engines Helper Addon.

Script 1
```
var x=copy;settings.SearchEnginesBrowserProxyImpl.prototype.getSearchEnginesList().then((searchEngines) => { x(JSON.stringify(searchEngines)); });
```

### Separate solution:

I. Go to `chrome://settings/`
II. Press F12
III. Paste Script 2 and press Enter.
IV. Open the downloaded file from the Firefox Search Engines Helper Addon.

Script 2
```
(function exportSEs() {
    /* Auxiliary function to download a file with the exported data */
    function downloadData(filename, data) {
        const file = new File([data], { type: 'text/json' });
        const elem = document.createElement('a');
        elem.href = URL.createObjectURL(file);
        elem.download = filename;
        elem.click();
    }

    /* Actual search engine export magic */
    settings.SearchEnginesBrowserProxyImpl.prototype.getSearchEnginesList()
        .then((searchEngines) => {
            var se = {};
            searchEngines.others.forEach(function (e) {
                se[e.displayName] = {
                    "searchURL": e.url,
                    "iconURL": e.iconURL
                };
            });

            downloadData('search_engines.json', JSON.stringify(se));
        });
}());
```

**Comment by soufianesakhi** [comment]
Thanks for the suggestion. I think it's more appropriate to adapt the external search engines sources to the current extension's format in order to support in the future many other providers.

I have created a wiki page for the instructions to import from Google Chrome based in your second solution (I fixed your script to manage some corner cases).
I added a link to this page in the main README.

**Comment by maxwowpow** [comment]
The fact behind my reasoning is that Chrome is used by most people now. And so potentially more switchers from Chrome as from all other browsers. And for normal users less code = easier solution.

![image](https://user-images.githubusercontent.com/169885/84444998-4a721c00-ac43-11ea-80d3-ae07bdecd850.png)

Nice work on the Icon URLs!
