### ISSUE TITLE
Show error information on screen in case of incorrect URL

### ISSUE THREAD

**Issue by AntonioRedondo** [soufianesakhi/firefox-search-engines-helper#17]
Thanks for this add-on. It's really frustrating how Firefox doesn't include any search engine export/import functionality and copying and pasting the `searchplugins` folder doesn't work any more. Your add-on is a life saver!

I found in your add-on some error handling functionality that perhaps should be refined. When an URL is introduced but it's incorrect or it doesn't contain the `%s` search term placeholder an ambiguous error is thrown in console. However this is an insufficient way of handling this kind of errors since you have to open the dev tools to know about them. And even so it's not clear what's the cause of the error.

I think these errors should be shown on the browser window below the _Add search engine_ button like on this mock-up:

![image](https://user-images.githubusercontent.com/5444421/97107894-d56b2480-16c1-11eb-9f54-15faa961cdaf.png)

**Comment by soufianesakhi** [comment]
Hello, thanks for the suggestions!
I will work on them shortly.

**Comment by soufianesakhi** [comment]
I have updated the addon to display input validation errors as notifications:
![Error handling](https://user-images.githubusercontent.com/17222854/97785790-98160380-1ba7-11eb-8f40-49b7d4e0dd0c.png)
