### ISSUE TITLE
BLOCKER: import no longer works in firefox

### ISSUE THREAD

**Issue by allanlaal** [soufianesakhi/firefox-search-engines-helper#21]
> Right-click inside the address bar, and select Add

Firefox changed something, "Add "searchenginename" is no longer available in urlbar right click menu

**Comment by soufianesakhi** [comment]
It's working on Windows with Firefox 96 & 97.
What's your operating system and Firefox version ?

**Comment by soufianesakhi** [comment]
Also can you confirm that the new search engine you want to add does not have a name matching an existing search engine in `about:preferences#search`  ?
