### ISSUE TITLE
Option to disable URL escaping

### ISSUE THREAD

**Issue by Forage** [soufianesakhi/firefox-search-engines-helper#22]
Using this add-on will URL escape the input before sending it to the defined site.
For some search engines the URL should not be escaped when it is a URL you are actually searching for.
I don't know if this behaviour is Firefox search related or add-on related though. If the latter is the case it would be good to have an option per search engine to prevent URL escaping.

Suppose you add the Wayback Machine as a search engine.
The URL would be "https://web.archive.org/web/*/%s", with a valid search query being "https://web.archive.org/web/*/https://example.com". Now the search query is being transformed to "https://web.archive.org/web/*/https%3A%2F%2Fexample.com" and the search will fail.

**Comment by soufianesakhi** [comment]
Unfortunately this is managed by the browser, no way to alter this behavior.
