### ISSUE TITLE
Option to test a search engine

### ISSUE THREAD

**Issue by Vingolf** [soufianesakhi/firefox-search-engines-helper#25]
Thank you for this useful extension 👍
It allows me to add more specific search engines to firefox.

For cases, when _a user is not satisfied with the results_ of a search string or
if the search string is incorrect,

 I propose to add

**An option to test a new search engine before it is added to firefox.**

This is related to  
*Show error information on screen in case of incorrect URL #17*

and gives the ability to improve a search string back to the user before it is added to firefox

**Comment by soufianesakhi** [comment]
Available in v3.3.0, check the new settings page
