### ISSUE TITLE
Add %S for unescaped search terms

### ISSUE THREAD

**Issue by A1ca7raz** [soufianesakhi/firefox-search-engines-helper#27]
I used to use Firefox bookmarks to manager my custom search engine and I was using %S to help me complete URL with unescaped search terms.

For example, I added a bookmark that URL is `https://github.com/%S` and keyword is `gh`, so I can type `gh soufianesakhi/firefox-search-engines-helper` that transforms to `https://github.com/soufianesakhi/firefox-search-engines-helper` to visit this repo quickly. It works on Firefox bookmarks but not on this extension.

If this feature can be implemented, I will appreciate it.

**Comment by soufianesakhi** [comment]
Hello,

This can't be implemented because there is no way to tell the browser to not escape the terms, see https://developer.mozilla.org/en-US/docs/Web/OpenSearch
