### ISSUE TITLE
not a bug: support request / question

### ISSUE THREAD

**Issue by bendover22** [soufianesakhi/firefox-search-engines-helper#4]
Thanks for the info.  One thing I'm not 100% sure of.  If the customized settings are in the xml plugin file, but (for argument's sake) don't show up in the URL bar.  Being a double naught spy, I wonder if sites you click on can see any of the search engine's set paramenters?  

Of course, if you use a custom settings bookmark, the search site can see it, but that's one reason to use engines that DON'T try to  profile you & log every keystroke. 

Someone suggested the FSEH addon to either export installed search plugins, edit them, then import back to search.json.moz1a4.  I used to use a similar (in description) addon - in pre-Quantum.

One problem I'm having is finding ALL the correct parameter names for some engines' settings.
Startpage.com - if you change default settings it shows 2 strings at page bottom (neither are xml - ready).  None are in the form: "&t=dark".  That's the "old style" for Startpage to select a non-default theme "dark."  There are a lot more  I can't find.  Some that are used in Open Search plugins on Mycroft Project don't seem to work.  Maybe some are deprecated by Startpage?

Startpage (not the only one I'm interested in) generates URLs after settings changes.  These are said to be for bookmarks or cookies, not in the format to enter in an xml search file.  But I see some submitted plugins on Mycroft, that enter the long, obfuscated string into the Post Paramenters field:
  `query={searchTerms}&cat=web&cmd=process_search&language=deutsch&engine0=v1allabp=-1prfe=67d6f7efcd45238dc5da976ba89cf2c11aad15df09559e990c1c89932309a9bc54b2adb3b1f304d36b63a5146635b4c9&op=un11&t=dawn.`  

 (That's supposed to be all one line).  The creator put the "op=un11&t=dawn" after the obfuscated string but they didn't work, till I moved them.
The custom URL will get you to the search site (maybe) if entered in the Open Search form.  I'm not sure it'll use the settings 

Some of the plugin creators then add older? style parameters (&cat=web) before & after the obfuscated string, starting: "prfe=" followed by a long string.  From what I could tell, the old parameters using '&' aren't recognized if they come after the obfuscated string.  I move one before the obfuscated string & it then recognized it.  Others don't seem to work at all, no matter they're location.  May be deprecated.  Do you know how to find the abbreviated search parameter names & possible values for Startpage,  Searx.me?  I think DDG publishes a list of custom settings.

I've searched & never found a complete list of Startpage parameters.
I don't think the Open Search XML will use the settings parameters data in the form created by Startpage.  Didn't for me, trying some already submitted plugins.  Only settings of the "&t=dark" form worked, if they were in the correct spot.  Maybe they worked better before Quantum.  I haven't worked on custom search plugins for other engines since Firefox Quantum was released.

**Comment by soufianesakhi** [comment]
Hello,
- *Startpage.com*: the URL should be https://www.startpage.com/do/dsearch?query=%s&cat=web&pl=opensearch&language=english (source: https://www.startpage.com/en/opensearch.xml)
- *Searx.me*: https://searx.me/search?q=%s (source: https://searx.me/opensearch.xml)
