### ISSUE TITLE
export doesn't work

### ISSUE THREAD

**Issue by 532910** [soufianesakhi/firefox-search-engines-helper#6]
Firefox 64.0 (64-bit) @ Debian sid

I've selected search.json.mozlz4 file but there are no "Open" button.

![image](https://user-images.githubusercontent.com/14617699/51856882-e39bdd80-2341-11e9-8ab8-8c4f6ce7b08c.png)

**Comment by soufianesakhi** [comment]
It should automatically export after you select the `search.json.mozlz4` (no Open button is needed).
Can you see any error relating to the extension in the `Browser Console` (CTRL + SHIFT + J or via Settings > Web Developer > Browser Console) ?

**Comment by 532910** [comment]
```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

parseBrowserEngines/<          moz-extension://d2bdbc69-79eb-414d-a4bf-6e8c8d06a66a/settings.js:138:28
readMozlz4File/reader.onload   moz-extension://d2bdbc69-79eb-414d-a4bf-6e8c8d06a66a/settings.js:122:3
```

**Comment by soufianesakhi** [comment]
I think you are testing some edge cases (like issue #5).
In this case you selected an empty or corrupted file.
I will provide an error message for this case.

**Comment by 532910** [comment]
The file is empty, of course! Where do you think should I take it from? The addon doesn't create it. So I've  ```% touch search.json.mozlz4```

**Comment by soufianesakhi** [comment]
You should select it from your [Firefox profile](http://kb.mozillazine.org/Profile_folder_-_Firefox) folder (there is an (*) that explains this if you didn't see it).

**Comment by 532910** [comment]
I don't understand anything. The export action must ask user for a filename and save ("export") some data into this new file. There is already search.json.mozlz4 in my profile folder. And it already contains search engines data. What is the reason to export something into it?

**Comment by 532910** [comment]
Moreover, the writing to search.json.mozlz4 in the profile folder is 'import'.

**Comment by soufianesakhi** [comment]
Due to Firefox limitations, the "search.json.mozlz4" file must be manually selected from the profile because it actually contains the search engines that will be exported, no API is provided by Firefox to do so.

After selecting the "search.json.mozlz4" file from the profile folder, the "all-browser-engines.json" file will be available to download. This file contains all the search urls and icon urls for all search engines added to Firefox.

For more details, visit the full documentation here: https://github.com/soufianesakhi/firefox-search-engines-helper/blob/master/README.md

**Comment by 532910** [comment]
So the 'export' action just decompress mozlz4 into plain json. This is not an 'export'.
Moreover it's better to use mozlz4-edit for example to edit it.
I think it's better to remove export/import actions at all as they so complicated. And replace with a short explanation how to save and restore search.json.mozlz4.

**Comment by soufianesakhi** [comment]
Some users prefer the simplicity of just selecting a file instead of installing a whole new add-on and following whole other steps to save and restore search.json.mozlz4 (This is exactly the purpose of this extension: automation !)
