### ISSUE TITLE
Search engine adds "+" to searches; doesn't work on some sites

### ISSUE THREAD

**Issue by Smottz** [soufianesakhi/firefox-search-engines-helper#7]
Rottentomatoes.com has a search format that looks like this:
https://www.rottentomatoes.com/search/?search=%s

The problem is, the custom search engine generated adds a "+" sign to each multi-word search, so that a search for "Indiana Jones" ends up as:
https://www.rottentomatoes.com/search/?search=indiana+jones

This search yields no result. But if you search for the same phrase at Rottentomatoes.com, the resulting search is simply:
https://www.rottentomatoes.com/search/?search=indiana%20jones

This works just fine. Is there a way to adjust the custom search engine generation so that it does not add this plus sign? Thanks so much!

**Comment by soufianesakhi** [comment]
Hello,
I don't think it's possible from the extension itself.
The extension generates an [OpenSearch](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) file, and Firefox uses this file to import internally the search engine. From this point the extension has no control of how Firefox manages it's search engines.

The OpenSearch xml file contains the url of the search engine, in this case it's: https://www.rottentomatoes.com/search/?search={searchTerms}. There is no way to tell Firefox how it should separate the search terms (with '+' or '%20' etc.).

**Comment by soufianesakhi** [comment]
You can use the following extension to search selected text with a pop up as it doesn't rely on Firefox to open searches, and uses spaces instead of '+' as a separator: https://addons.mozilla.org/en-US/firefox/addon/swift-selection-search/

**Comment by Smottz** [comment]
Thank you, Soufiane. It's a recent development in Rottentomatoes, so perhaps you're right that they'll fix it on their end. And thank you for the suggested extension. Unfortunately, I need something I can input manually (I use search engines primarily through keyword shortcuts: "ro indiana jones" etc. to speed up searches without having to visit a site first). Here's hoping things resolve! :) Thanks again!
